import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Timer from "../components/timer/timer";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Launch Countdown</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Image
        className={styles.bgStars}
        src={"/static/bg-stars.svg"}
        alt='background'
        fill
        sizes='100vw'
      />

      <header className={styles.header}>
        <h1 className={styles.headerText}>WE`RE LAUNCHING SOON</h1>
      </header>
      <main className={styles.main}>
        <Timer />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
      <div className={styles.patternWrapper}>
        <Image
          className={styles.pattern}
          src={"/static/pattern-hills.svg"}
          alt='background purple hill pattern'
          fill
          sizes='50vw'
        />
      </div>
    </div>
  );
}
